title: Charles Burnett # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a results-orientated application team lead with experience in strategic planning, management and implementation of projects and programs to support business transformation.
  <br><br>
  Trained as a physical geography and landscape ecology researcher, I bring a holistic, systems approach to my work. I have a passion for supporting and leading communities and communities of practice.
  <br><br>
  <b>Awards</b><br/>
  <a href="https://employmentprograms.gww.gov.bc.ca/awards/staff-award/">BC Public Service 2020 Staff Award of Excellence Cultivating the Co-op Employee Experience</a>
  <a href="https://employmentprograms.gww.gov.bc.ca/awards/staff-award/">show coop_saoe_page.png</a>
  <br><br>
  <a href="https://www.linkedin.com/in/cburnett/" target="_blank">View My LinkedIn Profile</a>


theme: jekyll-theme-minimal
google_analytics: UA-158825473-1 # your Google Analytics tracking ID here
