title: Charles Nils Burnett # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A results-orientated application team lead with experience in the planning, management and implementation of projects and programs to support organizational, operational and technological business transformation. 
  <br><br>
  Trained as a physical geography and landscape ecology researcher, Charles brings a holistic, systems approach to my work. He has a passion for supporting and leading communities and communities of practice.
  <br><br>
  <a href="https://www.linkedin.com/in/cburnett/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
